
package PersonalityQuiz;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Lukas Hamm & Ashley Johnson Date: 12 / 19 / 2024
 * Final Project (GUI implementation)
 * Description: The GUI implementation for our project, which is a program that
 * acts as a personality quiz for users to take to see if they are on either the Dark Side
 * or Light Side of the Force from Star Wars. 
 */
public class QuizWiz extends javax.swing.JFrame {

    /**
     * Creates new form QuizWiz
     */
    private List<QuizQuestion> questions;
    private UserResponse userResponse;
    private int currentQuestionIndex = 0;

	//Questions for the personalit quiz
    public QuizWiz() {
        initComponents();
        userResponse = new UserResponse("Quiz Taker");
		//New array to store questions
        questions = new ArrayList<>();
        //Adding all questions for the Quiz
        questions.add(new QuizQuestion("You find an injured stranger. What do you do?",
                new String[]{"Help them.", "Ignore them.", "Harm them."},
                new int[]{2, 0, -2}));
        questions.add(new QuizQuestion("Your mentor advises patience, but an opportunity arises...",
                new String[]{"Wait patiently.", "Act rashly.", "Seize control."},
                new int[]{2, 0, -2}));
        questions.add(new QuizQuestion("A child has lost their parents in the crowd and they ask you for help. What is your response?",
                new String[]{"Follow them to help look for their parents.", "Act as if you never heard them.", "Tell them that 'That's their problem'."},
                new int[]{2, 0, -2}));
        questions.add(new QuizQuestion("Someone starts to bully you and your friends. What is your response?",
                new String[]{"Kill them with kindness.", "Do nothing.", "Start planning your revenge."},
                new int[]{2, 0, -2}));
        questions.add(new QuizQuestion("You see an elderly woman struggling to put her groceries in her car. What do you do?",
                new String[]{"Help her load the groceries in her car.", "Walk by and do nothing.", "Ask to help, then proceed to drop all her groceries on the ground & walk away."},
                new int[]{2, 0, -2}));
        questions.add(new QuizQuestion("After leaving the movie theater, you see someone's car battery has died and they are asking people to help them. What do you do?",
                new String[]{"Find the jumper cables you have in the back of your vehicle.", "Walk by and do nothing.", "Incorrectly hook up the jumper cables, thus causing more damage to their car battery"},
                new int[]{2, 0, -2}));
        displayQuestion();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        answerButton1 = new javax.swing.JButton();
        answerButton2 = new javax.swing.JButton();
        answerButton3 = new javax.swing.JButton();
        scoreLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personality Quiz");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        questionLabel1.setBackground(new java.awt.Color(255, 255, 255));
        questionLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        questionLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionLabel1.setText("Question goes here.");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 360));

        answerButton1.setBackground(new java.awt.Color(204, 204, 255));
        answerButton1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        answerButton1.setText("Option 1");
        answerButton1.setMaximumSize(new java.awt.Dimension(50, 26));
        answerButton1.setMinimumSize(new java.awt.Dimension(50, 26));
        answerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerButton1ActionPerformed(evt);
            }
        });

        answerButton2.setBackground(new java.awt.Color(204, 204, 255));
        answerButton2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        answerButton2.setText("Option 2");
        answerButton2.setMaximumSize(new java.awt.Dimension(100, 26));
        answerButton2.setMinimumSize(new java.awt.Dimension(100, 26));
        answerButton2.setPreferredSize(new java.awt.Dimension(100, 26));
        answerButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerButton2ActionPerformed(evt);
            }
        });

        answerButton3.setBackground(new java.awt.Color(204, 204, 255));
        answerButton3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        answerButton3.setText("Option 3 ");
        answerButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(answerButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(answerButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(answerButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(answerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(answerButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(answerButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        scoreLabel.setBackground(new java.awt.Color(255, 255, 255));
        scoreLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        scoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel.setText("Light Side: 0 | Dark Side: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(questionLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addComponent(scoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(questionLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answerButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerButton2ActionPerformed
        // TODO add your handling code here:
        processAnswer(1);
    }//GEN-LAST:event_answerButton2ActionPerformed

    private void answerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerButton1ActionPerformed
        // TODO add your handling code here:
        processAnswer(0);
    }//GEN-LAST:event_answerButton1ActionPerformed

    private void answerButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerButton3ActionPerformed
        // TODO add your handling code here:
        processAnswer(2);
    }//GEN-LAST:event_answerButton3ActionPerformed

    //Method to display each Question and its answers
    private void displayQuestion() {
        if (currentQuestionIndex < questions.size()) {
            QuizQuestion current = questions.get(currentQuestionIndex);
            questionLabel1.setText(current.getQuestionText());

            // Update button text
            String[] choices = current.getAnswerChoices();
            answerButton1.setText(choices[0]);
            answerButton2.setText(choices[1]);
            answerButton3.setText(choices.length > 2 ? choices[2] : "");
        } else {
            displayResults();
        }
    }
    
    //Method to process the answer based on the current question
    private void processAnswer(int answerIndex) {
        QuizQuestion current = questions.get(currentQuestionIndex);
        userResponse.processAnswer(answerIndex, current);
        
        updateScoreLabel();

        currentQuestionIndex++;
        displayQuestion(); // Move to the next question
    }
    //Method to display the results of the Quiz after the final question
    private void displayResults() {
        questionLabel1.setText("Quiz Complete!");
        answerButton1.setVisible(false);
        answerButton2.setVisible(false);
        answerButton3.setVisible(false);

        int light = userResponse.getLightSide();
        int dark = userResponse.getDarkSide();
        String resultMessage;

        if (light > dark) {
            resultMessage = "The Light Side of the Force is strong within you!";
        } else {
            resultMessage = "You are corrupted by the Dark Side of the Force!";
        }
        scoreLabel.setText("Results: " + resultMessage);
    }
    private void updateScoreLabel() {
    int light = userResponse.getLightSide();
    int dark = userResponse.getDarkSide();
    scoreLabel.setText("Light Side: " + light + " | Dark Side: " + dark);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizWiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizWiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizWiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizWiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizWiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerButton1;
    private javax.swing.JButton answerButton2;
    private javax.swing.JButton answerButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel questionLabel1;
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables
}
